// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0E9OCcy0qaZwdQR4H6wd-WqvJU4WH1Ag',
    appId: '1:1057575228681:web:3edb5032536bf268082fd8',
    messagingSenderId: '1057575228681',
    projectId: 'vibenow-87b0a',
    authDomain: 'vibenow-87b0a.firebaseapp.com',
    storageBucket: 'vibenow-87b0a.appspot.com',
    measurementId: 'G-QZLPSTMQ5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt-3pKPUw9_mvQDAxJfFiLpeuo9UzCMoA',
    appId: '1:1057575228681:android:fc6f7a7e0710f45d082fd8',
    messagingSenderId: '1057575228681',
    projectId: 'vibenow-87b0a',
    storageBucket: 'vibenow-87b0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEtQktFlPqY-jP8JSvZQFO5PPXzI7whxA',
    appId: '1:1057575228681:ios:523df19e879cad2d082fd8',
    messagingSenderId: '1057575228681',
    projectId: 'vibenow-87b0a',
    storageBucket: 'vibenow-87b0a.appspot.com',
    iosClientId: '1057575228681-snlm4grj0eja4m369b8bja03ntsifjqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeNow',
  );
}
